//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Day7.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Day7.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lf AND lq -&gt; ls
        ///iu RSHIFT 1 -&gt; jn
        ///bo OR bu -&gt; bv
        ///gj RSHIFT 1 -&gt; hc
        ///et RSHIFT 2 -&gt; eu
        ///bv AND bx -&gt; by
        ///is OR it -&gt; iu
        ///b OR n -&gt; o
        ///gf OR ge -&gt; gg
        ///NOT kt -&gt; ku
        ///ea AND eb -&gt; ed
        ///kl OR kr -&gt; ks
        ///hi AND hk -&gt; hl
        ///au AND av -&gt; ax
        ///lf RSHIFT 2 -&gt; lg
        ///dd RSHIFT 3 -&gt; df
        ///eu AND fa -&gt; fc
        ///df AND dg -&gt; di
        ///ip LSHIFT 15 -&gt; it
        ///NOT el -&gt; em
        ///et OR fe -&gt; ff
        ///fj LSHIFT 15 -&gt; fn
        ///t OR s -&gt; u
        ///ly OR lz -&gt; ma
        ///ko AND kq -&gt; kr
        ///NOT fx -&gt; fy
        ///et RSHIFT 1 -&gt; fm
        ///eu OR fa -&gt; fb
        ///dd RSHIFT 2 -&gt; de
        ///NOT go -&gt; gp
        ///kb AND kd [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Input {
            get {
                return ResourceManager.GetString("Input", resourceCulture);
            }
        }
    }
}
