//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Day12.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Day12.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;e&quot;:[[{&quot;e&quot;:86,&quot;c&quot;:23,&quot;a&quot;:{&quot;a&quot;:[120,169,&quot;green&quot;,&quot;red&quot;,&quot;orange&quot;],&quot;b&quot;:&quot;red&quot;},&quot;g&quot;:&quot;yellow&quot;,&quot;b&quot;:[&quot;yellow&quot;],&quot;d&quot;:&quot;red&quot;,&quot;f&quot;:-19},{&quot;e&quot;:-47,&quot;a&quot;:[2],&quot;d&quot;:{&quot;a&quot;:&quot;violet&quot;},&quot;c&quot;:&quot;green&quot;,&quot;h&quot;:&quot;orange&quot;,&quot;b&quot;:{&quot;e&quot;:59,&quot;a&quot;:&quot;yellow&quot;,&quot;d&quot;:&quot;green&quot;,&quot;c&quot;:47,&quot;h&quot;:&quot;red&quot;,&quot;b&quot;:&quot;blue&quot;,&quot;g&quot;:&quot;orange&quot;,&quot;f&quot;:[&quot;violet&quot;,43,168,78]},&quot;g&quot;:&quot;orange&quot;,&quot;f&quot;:[{&quot;e&quot;:[82,-41,2,&quot;red&quot;,&quot;violet&quot;,&quot;orange&quot;,&quot;yellow&quot;],&quot;c&quot;:&quot;green&quot;,&quot;a&quot;:77,&quot;g&quot;:&quot;orange&quot;,&quot;b&quot;:147,&quot;d&quot;:49,&quot;f&quot;:&quot;blue&quot;},-1,142,136,[&quot;green&quot....
        /// </summary>
        internal static string Input {
            get {
                return ResourceManager.GetString("Input", resourceCulture);
            }
        }
    }
}
