//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Day2.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Day2.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4x23x21
        ///22x29x19
        ///11x4x11
        ///8x10x5
        ///24x18x16
        ///11x25x22
        ///2x13x20
        ///24x15x14
        ///14x22x2
        ///30x7x3
        ///30x22x25
        ///29x9x9
        ///29x29x26
        ///14x3x16
        ///1x10x26
        ///29x2x30
        ///30x10x25
        ///10x26x20
        ///1x2x18
        ///25x18x5
        ///21x3x24
        ///2x5x7
        ///22x11x21
        ///11x8x8
        ///16x18x2
        ///13x3x8
        ///1x16x19
        ///19x16x12
        ///21x15x1
        ///29x9x4
        ///27x10x8
        ///2x7x27
        ///2x20x23
        ///24x11x5
        ///2x8x27
        ///10x28x10
        ///24x11x10
        ///19x2x12
        ///27x5x10
        ///1x14x25
        ///5x14x30
        ///15x26x12
        ///23x20x22
        ///5x12x1
        ///9x26x9
        ///23x25x5
        ///28x16x19
        ///17x23x17
        ///2x27x20
        ///18x27x13
        ///16x7x18
        ///22x7x29
        ///17x28x6
        ///9x22x17
        ///10x5x6
        ///14x2x12
        ///25x5x [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Input {
            get {
                return ResourceManager.GetString("Input", resourceCulture);
            }
        }
    }
}
