//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Day3.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Day3.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ^^&lt;&lt;v&lt;&lt;v&gt;&lt;v^^&lt;&gt;&lt;&gt;^^&lt;v&lt;v^&gt;&gt;^^^&gt;&lt;^&gt;v^&gt;v&gt;&lt;&gt;&lt;&gt;&lt;&lt;vv^^&lt;^&gt;^^&lt;v^&gt;v&gt;v^v&gt;&gt;&gt;^&lt;&gt;v&lt;^&lt;v^&gt;&lt;^&gt;&gt;&gt;&gt;&gt;&lt;&lt;v&gt;&gt;^&gt;&gt;^&gt;v^&gt;&gt;&lt;&lt;^&gt;v&gt;v&lt;&gt;^v^v^vvv&gt;&lt;&gt;^^&gt;v&gt;&lt;v&lt;&gt;&lt;&gt;^&gt;&lt;^^&lt;vv^v&lt;v&gt;^v&gt;&gt;^v^&gt;v&gt;&lt;&gt;v^&lt;vv&gt;^&gt;&lt;&lt;v^&gt;vv^&lt;&lt;&gt;v&gt;&gt;&gt;&lt;&lt;&lt;&gt;&gt;^&lt;vv&lt;^&lt;&gt;^^vv&gt;&gt;&gt;^&gt;&lt;&lt;&lt;&lt;vv^v^&gt;&gt;&gt;&lt;&gt;&lt;^&gt;v&lt;&gt;^&gt;v&lt;v^v&lt;^vv&gt;&lt;^v^&gt;&lt;&lt;&lt;&lt;&gt;^&lt;&gt;v&gt;^v&gt;v&lt;v&lt;v&lt;&lt;&gt;v&lt;^&lt;&lt;&lt;v&gt;&gt;&gt;&gt;&gt;^^v&gt;vv^^&lt;&gt;^&lt;&gt;^^^^&lt;^^^v&lt;v^^&gt;v&lt;^^v^^&gt;v&gt;^v^^^^&gt;&gt;&lt;&lt;v&lt;&gt;v&lt;&gt;^v^&lt;v&lt;&gt;&gt;&lt;&gt;^^&gt;&lt;&lt;^^&lt;^^&gt;vv&lt;&gt;v^&lt;^v&lt;vv&lt;&lt;&lt;&gt;^&gt;^^&gt;^&lt;&gt;v^^vv&lt;&gt;&gt;v&gt;&lt;&lt;&lt;&gt;vvv&lt;&gt;v&lt;&gt;&gt;&lt;^&lt;^v&lt;&gt;^vv&gt;^....
        /// </summary>
        internal static string Input {
            get {
                return ResourceManager.GetString("Input", resourceCulture);
            }
        }
    }
}
