//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Day9.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Day9.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;sjdivfriyaaqa\xd2v\&quot;k\&quot;mpcu\&quot;yyu\&quot;en&quot;
        ///&quot;vcqc&quot;
        ///&quot;zbcwgmbpijcxu\&quot;yins\&quot;sfxn&quot;
        ///&quot;yumngprx&quot;
        ///&quot;bbdj&quot;
        ///&quot;czbggabkzo\&quot;wsnw\&quot;voklp\&quot;s&quot;
        ///&quot;acwt&quot;
        ///&quot;aqttwnsohbzian\&quot;evtllfxwkog\&quot;cunzw&quot;
        ///&quot;ugvsgfv&quot;
        ///&quot;xlnillibxg&quot;
        ///&quot;kexh\&quot;pmi&quot;
        ///&quot;syvugow&quot;
        ///&quot;m\&quot;ktqnw&quot;
        ///&quot;yrbajyndte\\rm&quot;
        ///&quot;f\&quot;kak\x70sn\xc4kjri&quot;
        ///&quot;yxthr&quot;
        ///&quot;alvumfsjni\&quot;kohg&quot;
        ///&quot;trajs\x5brom\xf1yoijaumkem\&quot;\&quot;tahlzs&quot;
        ///&quot;\&quot;oedr\&quot;pwdbnnrc&quot;
        ///&quot;qsmzhnx\&quot;&quot;
        ///&quot;\&quot;msoytqimx\\tbklqz&quot;
        ///&quot;mjdfcgwdshrehgs&quot;
        ///&quot;\&quot;rivyxahf\&quot;&quot;
        ///&quot;ciagc\x04bp&quot;
        ///&quot;xkfc&quot;
        ///&quot;xrgcripdu\x4c\xc4gszjhrvumvz\&quot;mngbirb&quot;
        ///&quot;gvmae\&quot;yiiu [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Input {
            get {
                return ResourceManager.GetString("Input", resourceCulture);
            }
        }
    }
}
